version: 2

defaults: &defaults
  working_directory: ~/dd-trace-java
  resource_class: large
  docker:
    - image: circleci/openjdk:8

test_job: &test_job
  steps:
    - attach_workspace:
        at: .

    - run:
        name: Run Tests
        command: GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2G -Xms512M" ./gradlew -g=gradle-home test --parallel --stacktrace --no-daemon --max-workers=3

    - run:
        name: Save Artifacts to (project-root)/build
        when: always
        command: .circleci/save_artifacts.sh

    - store_test_results:
        path: build/test-results

    - store_artifacts:
        path: build

    - persist_to_workspace:
        root: .
        paths: .

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          # Reset the cache approx every release
          keys:
            - dd-trace-java-{{ checksum "dd-trace-java.gradle" }}-{{ .Branch }}-{{ .Revision }}-verified
            - dd-trace-java-{{ checksum "dd-trace-java.gradle" }}-{{ .Branch }}-{{ .Revision }}
            - dd-trace-java-{{ checksum "dd-trace-java.gradle" }}-{{ .Branch }}
            - dd-trace-java-{{ checksum "dd-trace-java.gradle" }}
            - dd-trace-java

      - run:
          name: Build Project
          command: GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2G -Xms512M" ./gradlew -g=gradle-home clean check -x test --stacktrace --no-daemon

      - save_cache:
          key: dd-trace-java-{{ checksum "dd-trace-java.gradle" }}-{{ .Branch }}-{{ .Revision }}
          paths: gradle-home
          background: true

      - persist_to_workspace:
          root: .
          paths: .

#  test_7:
#    <<: *defaults
#    docker:
#      - image: openjdk:7-jdk
#
#    steps:
#      - attach_workspace:
#          at: .
#
#      - run:
#          name: Fix EC parameters error # (ref https://github.com/travis-ci/travis-ci/issues/8503)
#          command: |
#            wget "https://downloads.bouncycastle.org/java/bcprov-ext-jdk15on-158.jar" -O "${JAVA_HOME}"/jre/lib/ext/bcprov-ext-jdk15on-158.jar && \
#            perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security && \
#            echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | tee -a /etc/java-7-openjdk/security/java.security
#
#      - run:
#          name: Run Tests
#          command: GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2G -Xms512M" ./gradlew -g=gradle-home test --parallel --stacktrace --no-daemon --max-workers=3
#
#      - run:
#          name: Save Artifacts to (project-root)/build
#          when: always
#          command: .circleci/save_artifacts.sh
#
#      - store_test_results:
#          path: build/test-results
#
#      - store_artifacts:
#          path: build

  test_8:
    <<: *defaults
    <<: *test_job
    docker:
      - image: circleci/openjdk:8-jdk

#  test_9:
#    <<: *defaults
#    <<: *test_job
#    docker:
#      - image: circleci/openjdk:9-jdk

  scan_and_save:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Verify Version Scan
          command: ./gradlew -g=gradle-home verifyVersionScan --parallel --stacktrace --no-daemon

      - run:
          name: Save Artifacts to (project-root)/build
          when: always
          command: .circleci/save_artifacts.sh

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build

      - save_cache:
          key: dd-trace-java-{{ checksum "dd-trace-java.gradle" }}-{{ .Branch }}-{{ .Revision }}-verified
          paths: gradle-home

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Decode Signing Key
          command: echo $PGP_KEY_FILE | base64 --decode > /home/circleci/dd-trace-java/.circleci/secring.gpg

      - deploy:
          name: Publish master to Artifactory
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./gradlew -g=gradle-home -Psigning.keyId=${PGP_KEY_ID} \
                -Psigning.password=${PGP_KEY_PASS} \
                -Psigning.secretKeyRingFile=/home/circleci/dd-trace-java/.circleci/secring.gpg \
                -PbintrayUser=${BINTRAY_USER} \
                -PbintrayApiKey=${BINTRAY_API_KEY} \
                -PbuildInfo.build.number=${CIRCLE_BUILD_NUM} \
                artifactoryPublish --max-workers=1 --stacktrace --no-daemon
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build

#      - test_7:
#          requires:
#            - build
      - test_8:
          requires:
            - build
#      - test_9:
#          requires:
#            - build

      - scan_and_save:
          requires:
            - build
#            - test_7
            - test_8
#            - test_9

      - deploy:
          requires:
            - scan_and_save
          filters:
            branches:
              only: master
