version: 2
jobs:
  build:

    working_directory: ~/dd-trace-java

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - restore_cache:
          key: 'dd-trace-java-{{ checksum "pom.xml" }}-{{ checksum "dd-java-agent/pom.xml" }}-{{ checksum "dd-trace/pom.xml" }}'

      - run: mvn -q install -DskipTests dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: 'dd-trace-java-{{ checksum "pom.xml" }}-{{ checksum "dd-java-agent/pom.xml" }}-{{ checksum "dd-trace/pom.xml" }}'

      - run: mvn package

      - store_test_results:
          path: dd-java-agent/target/surefire-reports
      - store_test_results:
          path: dd-java-agent-ittests/target/surefire-reports
      - store_test_results:
          path: dd-trace/target/surefire-reports

      - store_artifacts:
          path: dd-java-agent/target/dd-java-agent.jar
